/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpmRouteImport } from './routes/upm'
import { Route as TryItRouteImport } from './routes/try-it'
import { Route as SidemapDotxmlRouteImport } from './routes/sidemap[.]xml'
import { Route as SeminariosRouteImport } from './routes/seminarios'
import { Route as RootedconRouteImport } from './routes/rootedcon'
import { Route as MakeItRouteImport } from './routes/make-it'
import { Route as InnovaTsnRouteImport } from './routes/innova-tsn'
import { Route as IndexRouteImport } from './routes/index'

const UpmRoute = UpmRouteImport.update({
  id: '/upm',
  path: '/upm',
  getParentRoute: () => rootRouteImport,
} as any)
const TryItRoute = TryItRouteImport.update({
  id: '/try-it',
  path: '/try-it',
  getParentRoute: () => rootRouteImport,
} as any)
const SidemapDotxmlRoute = SidemapDotxmlRouteImport.update({
  id: '/sidemap.xml',
  path: '/sidemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeminariosRoute = SeminariosRouteImport.update({
  id: '/seminarios',
  path: '/seminarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RootedconRoute = RootedconRouteImport.update({
  id: '/rootedcon',
  path: '/rootedcon',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeItRoute = MakeItRouteImport.update({
  id: '/make-it',
  path: '/make-it',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovaTsnRoute = InnovaTsnRouteImport.update({
  id: '/innova-tsn',
  path: '/innova-tsn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/innova-tsn': typeof InnovaTsnRoute
  '/make-it': typeof MakeItRoute
  '/rootedcon': typeof RootedconRoute
  '/seminarios': typeof SeminariosRoute
  '/sidemap.xml': typeof SidemapDotxmlRoute
  '/try-it': typeof TryItRoute
  '/upm': typeof UpmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/innova-tsn': typeof InnovaTsnRoute
  '/make-it': typeof MakeItRoute
  '/rootedcon': typeof RootedconRoute
  '/seminarios': typeof SeminariosRoute
  '/sidemap.xml': typeof SidemapDotxmlRoute
  '/try-it': typeof TryItRoute
  '/upm': typeof UpmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/innova-tsn': typeof InnovaTsnRoute
  '/make-it': typeof MakeItRoute
  '/rootedcon': typeof RootedconRoute
  '/seminarios': typeof SeminariosRoute
  '/sidemap.xml': typeof SidemapDotxmlRoute
  '/try-it': typeof TryItRoute
  '/upm': typeof UpmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/innova-tsn'
    | '/make-it'
    | '/rootedcon'
    | '/seminarios'
    | '/sidemap.xml'
    | '/try-it'
    | '/upm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/innova-tsn'
    | '/make-it'
    | '/rootedcon'
    | '/seminarios'
    | '/sidemap.xml'
    | '/try-it'
    | '/upm'
  id:
    | '__root__'
    | '/'
    | '/innova-tsn'
    | '/make-it'
    | '/rootedcon'
    | '/seminarios'
    | '/sidemap.xml'
    | '/try-it'
    | '/upm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InnovaTsnRoute: typeof InnovaTsnRoute
  MakeItRoute: typeof MakeItRoute
  RootedconRoute: typeof RootedconRoute
  SeminariosRoute: typeof SeminariosRoute
  SidemapDotxmlRoute: typeof SidemapDotxmlRoute
  TryItRoute: typeof TryItRoute
  UpmRoute: typeof UpmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upm': {
      id: '/upm'
      path: '/upm'
      fullPath: '/upm'
      preLoaderRoute: typeof UpmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try-it': {
      id: '/try-it'
      path: '/try-it'
      fullPath: '/try-it'
      preLoaderRoute: typeof TryItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidemap.xml': {
      id: '/sidemap.xml'
      path: '/sidemap.xml'
      fullPath: '/sidemap.xml'
      preLoaderRoute: typeof SidemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seminarios': {
      id: '/seminarios'
      path: '/seminarios'
      fullPath: '/seminarios'
      preLoaderRoute: typeof SeminariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rootedcon': {
      id: '/rootedcon'
      path: '/rootedcon'
      fullPath: '/rootedcon'
      preLoaderRoute: typeof RootedconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make-it': {
      id: '/make-it'
      path: '/make-it'
      fullPath: '/make-it'
      preLoaderRoute: typeof MakeItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innova-tsn': {
      id: '/innova-tsn'
      path: '/innova-tsn'
      fullPath: '/innova-tsn'
      preLoaderRoute: typeof InnovaTsnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InnovaTsnRoute: InnovaTsnRoute,
  MakeItRoute: MakeItRoute,
  RootedconRoute: RootedconRoute,
  SeminariosRoute: SeminariosRoute,
  SidemapDotxmlRoute: SidemapDotxmlRoute,
  TryItRoute: TryItRoute,
  UpmRoute: UpmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
